name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/UMKM-Malang

            git pull origin main

            composer install --no-interaction --prefer-dist --optimize-autoloader

            cp .env.example .env || true
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear

            php artisan migrate --force

            npm install
            npm run build

            chown -R www-data:www-data /var/www/UMKM-Malang
            chmod -R 775 /var/www/UMKM-Malang/storage /var/www/UMKM-Malang/bootstrap/cache
          EOF
