name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti jika kamu pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync project via rsync
        run: |
          rsync -avz --exclude=node_modules \
                     --exclude=.git \
                     --exclude=storage/logs/* \
                     ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/UMKM-Malang

      - name: Run Laravel commands on server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/UMKM-Malang
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            chown -R faizhenri:www-data .
            chmod -R ug+rwX storage bootstrap/cache
          EOF
